# Generated by Django 5.2.1 on 2025-07-02 14:33

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_atencion_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioatencion',
            name='dia_semana',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], max_length=52, verbose_name='Día de la Semana'),
        ),
    ]
