# Generated by Django 5.2.1 on 2025-07-03 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_horarioatencion_dia_semana'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horarioatencion',
            unique_together=set(),
        ),
    ]
